name: askhim

services:
  askhim:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FLAG=flag{4M4_CSS_CSRF_XSS_M4ST3R_6f831203}
      - TOKEN=6f83120307457af3753ff772933072fbdf44006bd817e53dc082af0fd54615ce

  bot:
    restart: always
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - API_URL=askhim:3000
      - TOKEN=6f83120307457af3753ff772933072fbdf44006bd817e53dc082af0fd54615ce
      - OPENROUTER_API_KEY=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
    depends_on:
      - askhim
